### ISSUE TITLE
What version of POI class have you been testing with ?

### ISSUE THREAD

**Issue by nadl40** [cy2hq/CY2_SpreadSheet#1]
I have POI version 3.17 and can't get the classes

```
136      11:17:48.335     0.000132        4:    Local JavaObject &workbookFactory = GetJavaClass("org.apache.poi.ss.usermodel.WorkbookFactory");
137      11:17:48.336     0.000133                Str[43]=org.apache.poi.ss.usermodel.Wo
138      11:17:52.721     4.385333 ErrorReturn-> 725 - Java Exception: java.lang.OutOfMemoryError: GC overhead limit exceeded: finding class PeopleSoft/PeopleCode/Func (2,725) CY2_SPREADSHEET.Workbook.OnExecute  Name:Workbook  PCPC:175  Statement:4

```

Version 3.17 does not include WorkbookFactory as far as I can see.
 - PeopleTools: 8.58 
 - PeopleSoft Version: 9.2

Thanks; George

**Comment by cuda** [comment]
Dang, I never saw this. Sorry, this was tested originally with 8.57. We have a newer version that works 8.60 that I'll post soon,

**Comment by cuda** [comment]
Side note, in the new version, we've added a StreamingWorkbook class. We were also getting an out of memory error when writing large files.
