### ISSUE TITLE
GetCellType not working within methods.

### ISSUE THREAD

**Issue by scotthicks92** [cy2hq/CY2_SpreadSheet#2]
Hi;

Recently loaded this app package and it is working great. Except I just ran into an issue where the GetCellType that used to return a constant (ie. NUMERIC, STRING) know returns a CellType object.  In this version the logic that compares a cell type fails with a TYPE issue.  I was wondering if there is a newer version that works with the new POI version of javascript?  I tried the suggested GetCellTypeEnum but it is also deprecated.

Scott

example from current version:
method GetCellNumber
   /+ &row as Integer, +/
   /+ &column as Integer, +/
   /+ &value as Number out +/
   /+ Returns Boolean +/
   Local JavaObject &cell = %This.GetCell(&row, &column);
   If &cell = Null Then
      Return False;
   End-If;
   
   Local boolean &success = False;
   **Evaluate &cell.getCellType()
   When &NumericCell**
      &value = &cell.getNumericCellValue();
      &success = True;
      Break;
      
   When &StringCell
      try
         &value = Value(&cell.getStringCellValue());
         &success = True;
      catch Exception &exp

**Comment by cuda** [comment]
Hi Scott,

What version of PeopleTools are you using? Can you provide a code snippet that replicates your problem?

>  I was wondering if there is a newer version that works with the new POI version of javascript?

Could you point to a version of POI for javascript?

Thanks,
Marcus

**Comment by scotthicks92** [comment]
Hi Marcus;

Would like to thank you for responding so quickly.

We are on the most recent PTools and must be very new POI code as the other
methods are deprecated. I could ask the PSADMIN if you like.

I was talking with a couple other people in the meantime and they gave me a
solution that is working.

Since the POI had changed in the newest version. The GetCellType method
returns a CellType object now and not the integer value it did before.
ANd GetCellTypeEnum is also deprecated in our POI version.

They told me to use:

evaluate &cell.getCellType()*.name()*    (It returns a string of the enum
value)
when "NUMERIC"
---
when "STRING"
---

end-evaluate;

In your app package (which by the way is working great) I am replacing your
evaluate &cell.GetCellType ......  With what I mentioned above.

Scott

**Comment by cuda** [comment]
right, that is what we do in the new version. I committed it a couple hours ago.
